#=============================================================================
# Spiros kabasakalis
# Configuration for SpaceVim, also see autoload/config_before.vim
#
# Author: Spiros kabasakalis < kabasakalis at gmail.com >
# URL: https://github.com/kabasakalis
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  # colorscheme = "OceanicNext"
  # colorscheme = "gruvbox"
  colorscheme = "deep-space"
  # colorscheme = "zenburn"
  # colorscheme = "gotham"
  # colorscheme = "iceberg"
  # colorscheme =  "Tomorrow-Night"
  # colorscheme = "chocolate"
  # colorscheme = "onehalfdark"
  # colorscheme = "despacio"
  # colorscheme = "base16-tomorrow-night"
  # colorscheme = "jellybeans"
  # colorscheme = "PaperColor"
  # colorscheme = "nord"
  # colorscheme = "one"
  # colorscheme = "material"
  background = "dark"

  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts: arrow, curve, slant, nil, fire
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  #Use ale for syntax checking, disabled by default.(Used only for C++)
  enable_ale = false
  terminal_cursor_shape = 1
  # Set the guifont of SpaceVim. Default is DejaVu Sans Mono For Powerline
  # NOTE: On windows only fixed width fonts are allowed.
  # NOTE 2: You need Nerd Fonts for devicons plugin to work.
  # guifont = "DejaVu Sans Mono for Powerline:h10"
  guifont = "DejaVuSansMono NF:h10"
  # guifont = "LiterationMono NF:h10"
  # guifont = "SauceCodePro Nerd Font:h10"
  #Enable/Disable relativenumber, by default it is enabled.
  relativenumber = false
  enable_language_specific_leader = 1
  bootstrap_before = "config_before#before"
  bootstrap_after = "config_after#after"
  project_rooter_automatically = 0
  #vimcompatible = true
  #snippet_engine
  snippet_engine = "ultisnips"
  filemanager = "nerdtree"

  # disabled_plugins = ["vimproc"]
  # disabled_plugins = ["deoplete", "neoformat"]
  # the default value is vimfiler

[[layers]]
  name = 'denite'
# Enable autocomplete layer
# CAUTION: Disable this if using coc.vim for autocompletion!
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"
  enable = false
[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30
[[layers]]
  name = "colorscheme"
    # random_theme = true
    # frequency = '1m'
[[layers]]
  name = "tmux"
[[layers]]
  name = "lang#c"
  # clang_executable = "/usr/bin/clang"
  clang_executable = "F:\Programs\LLVM\bin\clang.exe"
  enable = false
[layer.clang_std]
  c = "c11"
  # cpp = "c++1z"
  cpp = "c++17"
  objc = "c11"
  objcpp = "c++1z"
  enable = false

# add custom_plugins: https://github.com/mhartington/oceanic-next
[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0

[[custom_plugins]]
  name = "simeji/winresizer"
  merged = 0

[[custom_plugins]]
  name = "bkad/CamelCaseMotion"
  merged = 0

[[custom_plugins]]
    name = "lilydjwg/colorizer"
    on_cmd = ["ColorHighlight", "ColorToggle"]
    merged = 0

[[custom_plugins]]
  name = "ryanoasis/vim-devicons"
  merged = 0

[[custom_plugins]]
  name = "octol/vim-cpp-enhanced-highlight"
  merged = 0

# To enable coc.vim also move coc.vim to plugin folder 
[[custom_plugins]]
  name = "neoclide/coc.nvim"
  merged = 0

[[custom_plugins]]
  name = "tpope/vim-git"
  merged = 0

[[custom_plugins]]
  name = "martin-svk/vim-yaml"
  merged = 0

[[custom_plugins]]
  name = "tpope/vim-markdown"
  merged = 0

[[custom_plugins]]
  name = "vim-scripts/tComment"
  merged = 0

[[custom_plugins]]
  name = "SirVer/ultisnips"
  merged = 0

[[custom_plugins]]
  name = "honza/vim-snippets"
  merged = 0

# [[custom_plugins]]
  # name = "uplus/vim-clang-rename"
  # merged = 0
